config/routes.rb
Layouts::Application.routes.draw do
  
  root :to => "home#index"
  
  match "/news" => "news#index", :via => :get
  

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "home"
  
  def index
    
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  
  layout "news"
  
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/home/index.html.erb
<h2>Home view</h2>
<p>
	
<%= link_to "News", news_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Layouts</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Layouts</title>
  <%= stylesheet_link_tag    "home", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "home", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<b>Home layout </b><br>

<%= yield %>

</body>
</html>

app/views/layouts/news.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Layouts</title>
  <%= stylesheet_link_tag    "news", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "news", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<b>News layout </b><br>

<%= yield %>

</body>
</html>

app/views/news/index.html.erb
<h2>News view<h2>
<p>
	
<%= link_to "Home", root_path %>